ALTER TABLE products ADD COLUMN IF NOT EXISTS sku VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS type VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS color VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS size VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS out_of_stock BOOLEAN DEFAULT FALSE;
