ALTER TABLE products ADD COLUMN IF NOT EXISTS has_warranty BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS warranty_details VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS warranty_claim_rules VARCHAR(500);
ALTER TABLE products ADD COLUMN IF NOT EXISTS use_custom_return_policy BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS custom_return_policy VARCHAR(500);

ALTER TABLE ai_settings ADD COLUMN IF NOT EXISTS global_return_policy TEXT;
ALTER TABLE ai_settings ADD COLUMN IF NOT EXISTS general_faq TEXT;

ALTER TABLE customers ADD COLUMN IF NOT EXISTS requires_human BOOLEAN DEFAULT FALSE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS requires_human_reason VARCHAR(255);
